-- Initial SQL migration for Prisma-like schema
CREATE TABLE "User" (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  role TEXT NOT NULL DEFAULT 'USER',
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT now(),
  "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE "Team" (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  description TEXT,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT now(),
  "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE "TeamMember" (
  id SERIAL PRIMARY KEY,
  "userId" INTEGER NOT NULL REFERENCES "User"(id) ON DELETE CASCADE,
  "teamId" INTEGER NOT NULL REFERENCES "Team"(id) ON DELETE CASCADE,
  role TEXT DEFAULT 'USER',
  UNIQUE("userId", "teamId")
);

CREATE TABLE "Project" (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  description TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT now(),
  "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now(),
  "ownerId" INTEGER NOT NULL REFERENCES "User"(id) ON DELETE RESTRICT,
  "teamId" INTEGER REFERENCES "Team"(id) ON DELETE SET NULL
);

CREATE TABLE "ProjectMember" (
  id SERIAL PRIMARY KEY,
  "userId" INTEGER NOT NULL REFERENCES "User"(id) ON DELETE CASCADE,
  "projectId" INTEGER NOT NULL REFERENCES "Project"(id) ON DELETE CASCADE,
  role TEXT DEFAULT 'CONTRIBUTOR',
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT now(),
  UNIQUE("userId", "projectId")
);

CREATE TABLE "Task" (
  id SERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  status TEXT NOT NULL DEFAULT 'TODO',
  priority INTEGER NOT NULL DEFAULT 3,
  "dueDate" TIMESTAMP WITH TIME ZONE,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT now(),
  "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now(),
  "projectId" INTEGER NOT NULL REFERENCES "Project"(id) ON DELETE CASCADE,
  "assigneeId" INTEGER REFERENCES "User"(id) ON DELETE SET NULL
);

CREATE INDEX idx_task_project ON "Task"("projectId");
CREATE INDEX idx_task_assignee ON "Task"("assigneeId");

CREATE TABLE "Comment" (
  id SERIAL PRIMARY KEY,
  content TEXT NOT NULL,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT now(),
  "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now(),
  "authorId" INTEGER NOT NULL REFERENCES "User"(id),
  "taskId" INTEGER NOT NULL REFERENCES "Task"(id) ON DELETE CASCADE
);

CREATE TABLE "Tag" (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);

CREATE TABLE "TaskTag" (
  id SERIAL PRIMARY KEY,
  "taskId" INTEGER NOT NULL REFERENCES "Task"(id) ON DELETE CASCADE,
  "tagId" INTEGER NOT NULL REFERENCES "Tag"(id),
  UNIQUE("taskId", "tagId")
);
